#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v22
# autospec commit: 247c192
#
# Source0 file verified with key 0x30A59377A7763BE6 (slouken@libsdl.org)
#
Name     : SDL3
Version  : 3.2.10
Release  : 2
URL      : https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.tar.gz
Source0  : https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.tar.gz
Source1  : https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-3.2.10.tar.gz.sig
Source2  : 30A59377A7763BE6.pkey
Summary  : C Library for USB/Bluetooth HID device access from Linux, Mac OS X, FreeBSD, and Windows.
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 ISC OFL-1.1
Requires: SDL3-data = %{version}-%{release}
Requires: SDL3-lib = %{version}-%{release}
Requires: SDL3-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : liburing-dev
BuildRequires : libxkbcommon-dev
BuildRequires : mesa-dev
BuildRequires : openjdk
BuildRequires : perl
BuildRequires : pipewire-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : python3-dev
BuildRequires : systemd-dev
BuildRequires : wayland-dev
BuildRequires : wayland-protocols-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Simple DirectMedia Layer (SDL for short) is a cross-platform library
designed to make it easy to write multi-media software, such as games
and emulators.

%package data
Summary: data components for the SDL3 package.
Group: Data

%description data
data components for the SDL3 package.


%package dev
Summary: dev components for the SDL3 package.
Group: Development
Requires: SDL3-lib = %{version}-%{release}
Requires: SDL3-data = %{version}-%{release}
Provides: SDL3-devel = %{version}-%{release}
Requires: SDL3 = %{version}-%{release}

%description dev
dev components for the SDL3 package.


%package lib
Summary: lib components for the SDL3 package.
Group: Libraries
Requires: SDL3-data = %{version}-%{release}
Requires: SDL3-license = %{version}-%{release}

%description lib
lib components for the SDL3 package.


%package license
Summary: license components for the SDL3 package.
Group: Default

%description license
license components for the SDL3 package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 30A59377A7763BE6' gpg.status
%setup -q -n SDL3-3.2.10
cd %{_builddir}/SDL3-3.2.10
pushd ..
cp -a SDL3-3.2.10 buildavx2
popd
pushd ..
cp -a SDL3-3.2.10 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1743459489
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd
pushd ../buildapx/
mkdir -p clr-build-apx
pushd clr-build-apx
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1743459489
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL3
cp %{_builddir}/SDL3-%{version}/src/hidapi/LICENSE-bsd.txt %{buildroot}/usr/share/package-licenses/SDL3/7dde42b4c6fdafae722d8d07556b6d9dba4d2963 || :
cp %{_builddir}/SDL3-%{version}/src/hidapi/LICENSE-gpl3.txt %{buildroot}/usr/share/package-licenses/SDL3/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/SDL3-%{version}/src/hidapi/LICENSE-orig.txt %{buildroot}/usr/share/package-licenses/SDL3/66047dbcf3fd689c99472266f5ad141c53d6f2c6 || :
cp %{_builddir}/SDL3-%{version}/src/video/yuv2rgb/LICENSE %{buildroot}/usr/share/package-licenses/SDL3/763a61ff74960ead36b9ef5f5db65d083d7466c1 || :
cp %{_builddir}/SDL3-%{version}/test/unifont-15.1.05-license.txt %{buildroot}/usr/share/package-licenses/SDL3/ee06847a47ae566e1f69859ef1b1621189c0e03c || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
pushd ../buildapx/
GOAMD64=v3
pushd clr-build-apx
%make_install_va  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/licenses/SDL3/LICENSE.txt

%files dev
%defattr(-,root,root,-)
/usr/include/SDL3/SDL.h
/usr/include/SDL3/SDL_assert.h
/usr/include/SDL3/SDL_asyncio.h
/usr/include/SDL3/SDL_atomic.h
/usr/include/SDL3/SDL_audio.h
/usr/include/SDL3/SDL_begin_code.h
/usr/include/SDL3/SDL_bits.h
/usr/include/SDL3/SDL_blendmode.h
/usr/include/SDL3/SDL_camera.h
/usr/include/SDL3/SDL_clipboard.h
/usr/include/SDL3/SDL_close_code.h
/usr/include/SDL3/SDL_copying.h
/usr/include/SDL3/SDL_cpuinfo.h
/usr/include/SDL3/SDL_dialog.h
/usr/include/SDL3/SDL_egl.h
/usr/include/SDL3/SDL_endian.h
/usr/include/SDL3/SDL_error.h
/usr/include/SDL3/SDL_events.h
/usr/include/SDL3/SDL_filesystem.h
/usr/include/SDL3/SDL_gamepad.h
/usr/include/SDL3/SDL_gpu.h
/usr/include/SDL3/SDL_guid.h
/usr/include/SDL3/SDL_haptic.h
/usr/include/SDL3/SDL_hidapi.h
/usr/include/SDL3/SDL_hints.h
/usr/include/SDL3/SDL_init.h
/usr/include/SDL3/SDL_intrin.h
/usr/include/SDL3/SDL_iostream.h
/usr/include/SDL3/SDL_joystick.h
/usr/include/SDL3/SDL_keyboard.h
/usr/include/SDL3/SDL_keycode.h
/usr/include/SDL3/SDL_loadso.h
/usr/include/SDL3/SDL_locale.h
/usr/include/SDL3/SDL_log.h
/usr/include/SDL3/SDL_main.h
/usr/include/SDL3/SDL_main_impl.h
/usr/include/SDL3/SDL_messagebox.h
/usr/include/SDL3/SDL_metal.h
/usr/include/SDL3/SDL_misc.h
/usr/include/SDL3/SDL_mouse.h
/usr/include/SDL3/SDL_mutex.h
/usr/include/SDL3/SDL_oldnames.h
/usr/include/SDL3/SDL_opengl.h
/usr/include/SDL3/SDL_opengl_glext.h
/usr/include/SDL3/SDL_opengles.h
/usr/include/SDL3/SDL_opengles2.h
/usr/include/SDL3/SDL_opengles2_gl2.h
/usr/include/SDL3/SDL_opengles2_gl2ext.h
/usr/include/SDL3/SDL_opengles2_gl2platform.h
/usr/include/SDL3/SDL_opengles2_khrplatform.h
/usr/include/SDL3/SDL_pen.h
/usr/include/SDL3/SDL_pixels.h
/usr/include/SDL3/SDL_platform.h
/usr/include/SDL3/SDL_platform_defines.h
/usr/include/SDL3/SDL_power.h
/usr/include/SDL3/SDL_process.h
/usr/include/SDL3/SDL_properties.h
/usr/include/SDL3/SDL_rect.h
/usr/include/SDL3/SDL_render.h
/usr/include/SDL3/SDL_revision.h
/usr/include/SDL3/SDL_scancode.h
/usr/include/SDL3/SDL_sensor.h
/usr/include/SDL3/SDL_stdinc.h
/usr/include/SDL3/SDL_storage.h
/usr/include/SDL3/SDL_surface.h
/usr/include/SDL3/SDL_system.h
/usr/include/SDL3/SDL_test.h
/usr/include/SDL3/SDL_test_assert.h
/usr/include/SDL3/SDL_test_common.h
/usr/include/SDL3/SDL_test_compare.h
/usr/include/SDL3/SDL_test_crc32.h
/usr/include/SDL3/SDL_test_font.h
/usr/include/SDL3/SDL_test_fuzzer.h
/usr/include/SDL3/SDL_test_harness.h
/usr/include/SDL3/SDL_test_log.h
/usr/include/SDL3/SDL_test_md5.h
/usr/include/SDL3/SDL_test_memory.h
/usr/include/SDL3/SDL_thread.h
/usr/include/SDL3/SDL_time.h
/usr/include/SDL3/SDL_timer.h
/usr/include/SDL3/SDL_touch.h
/usr/include/SDL3/SDL_tray.h
/usr/include/SDL3/SDL_version.h
/usr/include/SDL3/SDL_video.h
/usr/include/SDL3/SDL_vulkan.h
/usr/lib64/cmake/SDL3/SDL3Config.cmake
/usr/lib64/cmake/SDL3/SDL3ConfigVersion.cmake
/usr/lib64/cmake/SDL3/SDL3headersTargets.cmake
/usr/lib64/cmake/SDL3/SDL3sharedTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SDL3/SDL3sharedTargets.cmake
/usr/lib64/cmake/SDL3/SDL3testTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SDL3/SDL3testTargets.cmake
/usr/lib64/libSDL3.so
/usr/lib64/pkgconfig/sdl3.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libSDL3.so.0.2.10
/VA/usr/lib64/libSDL3.so.0.2.10
/usr/lib64/libSDL3.so.0
/usr/lib64/libSDL3.so.0.2.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL3/66047dbcf3fd689c99472266f5ad141c53d6f2c6
/usr/share/package-licenses/SDL3/763a61ff74960ead36b9ef5f5db65d083d7466c1
/usr/share/package-licenses/SDL3/7dde42b4c6fdafae722d8d07556b6d9dba4d2963
/usr/share/package-licenses/SDL3/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/SDL3/ee06847a47ae566e1f69859ef1b1621189c0e03c
